<?php

namespace WishBundle\Repository;

/**
 * wishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class wishRepository extends \Doctrine\ORM\EntityRepository
{
}
